# Generated by Django 3.0.2 on 2020-01-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadfield',
            name='paste_link',
        ),
        migrations.AddField(
            model_name='downloadfield',
            name='download_field',
            field=models.URLField(default=None, unique=True),
        ),
    ]
